### ISSUE TITLE
deprecated images in the vhd

### ISSUE THREAD

**Issue by sozercan** [Azure/AgentBaker#1220]
I believe these images are deprecated. Can someone from AKS double check and remove these if needed

```
mcr.microsoft.com/k8s/core/pause 
mcr.microsoft.com/k8s/flexvolume/blobfuse-flexvolume
mcr.microsoft.com/k8s/flexvolume/keyvault-flexvolume
mcr.microsoft.com/oss/kubernetes/exechealthz
```

**Comment by alexeldeib** [comment]
almost a year later, but mcr.microsoft.com/k8s/core/pause is gone..

**Comment by cameronmeissner** [comment]
the referenced images are no longer cached
