### ISSUE TITLE
only kubelet cached in the VHD can be picked for a specific version

### ISSUE THREAD

**Issue by mainred** [Azure/AgentBaker#1482]
When building the VHD, we extract the kubelet binary to `/usr/local/bin/` according to [install-dependencies.sh](https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/packer/install-dependencies.sh#L479), so that when we use CSE to install the exact kubelet from the user-input URL, like a hotfix,  the hotfix will be skipped for the existing kubelet binary with the same kubernetes version, achieved by [cse_install.sh](https://github.com/Azure/AgentBaker/blob/master/parts/linux/cloud-init/artifacts/cse_install.sh#L209). This brings less flexibility because only the cached kubelet can be used regardless of the user input, and we have to build a VHD in order to include the hotfixed kubelet.

**Comment by alexeldeib** [comment]
@mainred I'd welcome a PR to simply include the full hotfix. this would have big benefits Kubelet hotfixes for aks generally.

**Comment by cameronmeissner** [comment]
closing due to age and inactivity, feel free to re-open if necessary.
