### ISSUE TITLE
Update Windows CNI

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AgentBaker#1625]
https://github.com/Azure/azure-container-networking/releases/tag/v1.4.21 fixed a bug which occur frequently in our AKS clusters:
https://github.com/Azure/azure-container-networking/pull/1272
https://github.com/Azure/azure-container-networking/issues/831

Can you update Windows CNI asap?
@abelhu

**Comment by AbelHu** [comment]
@zhiweiv FYI: v1.4.21 has a bug so AKS cannot pick up it. Azure container networking team is fixing it.

**Comment by zhiweiv** [comment]
This issue have been last over one year, it is ok to wait a few more days:sob:.

**Comment by zhiweiv** [comment]
Is https://github.com/Azure/azure-container-networking/releases/tag/v1.4.22 ok to update?

**Comment by zhiweiv** [comment]
@AbelHu 
Do you know when will AKS 1.23 GA? I can see 1.20 is announced deprecated in AKS RP release v20220327, but no announcement for 1.23.

**Comment by AbelHu** [comment]
@zhiweiv AKS team is working on 1.23 GA. It should be coming very soon.
