### ISSUE TITLE
Details: version v0.20211030.0 is not supported for AgentBaker

### ISSUE THREAD

**Issue by owensrd** [Azure/AgentBaker#1759]
**What happened**: I was attempting to scale our Kubernetes node pool though the azure portal UI, when it failed with the following error:
    Details: version v0.20211030.0 is not supported for AgentBaker

**What you expected to happen**: I was expecting it to scale as it has in the past

**How to reproduce it**: Attempting to scale will result in the same error each time.

**Anything else we need to know?**: None that I can think of

**Environment**:
- AgentBaker version: v0.20211030.0
- Kubernetes version (use `kubectl version`): 1.21.2

**Comment by varnastadeus** [comment]
Having the same issue using `1.22.4`

**Comment by cameronmeissner** [comment]
closing due to age and inactivity
