### ISSUE TITLE
The file with the same name as the cached one won't be downloaded for Windows CSE

### ISSUE THREAD

**Issue by mainred** [Azure/AgentBaker#1832]
**What happened**:

During CSE phase,  `DownloadFileOverHttp`  will not download the file from the remote server and use the cached file instead, when the remote file has the same name as the cached one, even if they are not the same.

**What you expected to happen**:
The remote file will be downloaded if it's not the same one, or has the same md5, as the cached file.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- AgentBaker version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by AbelHu** [comment]
It is by design since AKS caches the expected package in the VHD.
