### ISSUE TITLE
Windows 2022_containerd_gen2 PR check failed for missing image but VHD build succeeded

### ISSUE THREAD

**Issue by HDYA** [Azure/AgentBaker#2147]
**What happened**:

 VHD build succeeded but Windows 2022_containerd_gen2 PR check failed for missing image

**What you expected to happen**:

image should exist

**How to reproduce it**:

https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=59900982&view=logs&j=05b0285b-7424-5da1-4fe4-29b48f7b1d3a&t=e2ed4504-bf94-5207-4338-b6117c41217b

```
ERROR: {"error":{"code":"InvalidTemplateDeployment","message":"The template deployment 'vm_deploy_lsPbsw0MGltObZiGrK6beKtGHaF2R7pi' is not valid according to the validation procedure. The tracking id is 'c5afa5c6-eda2-49c2-8251-24950ebf7fe6'. See inner errors for details.","details":[{"code":"InvalidParameter","target":"imageReference","message":"In region eastus, the following list of Shared Image Gallery images referenced from the deployment template were not found: /subscriptions/a15c116e-99e3-4c59-aebc-8f864929b4a0/resourceGroups/akswinvhdbuilderrg/providers/Microsoft.Compute/galleries/WS2022Gen2Gallery220902/images/windows-2022-containerd/versions/1.0.0. Please check that at least one image has been replicated to eastus or that the ‘exclude from latest’ flag is set to false. Please refer to https://docs.microsoft.com/en-us/azure/virtual-machines/windows/shared-image-galleries for instructions on creating and deleting such images."}]}}
```

**Anything else we need to know?**:

**Environment**:
- AgentBaker version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by HDYA** [comment]
could you help triage? @wanqingfu 
Thanks!

**Comment by wanqingfu** [comment]
> and deleting such i

Yeah. Did you find the gallery "WS2022Gen2Gallery220902" on the portal when you encountered this error? Looks like from the building step, this image exists. `"ManagedImageSharedImageGalleryId: /subscriptions/a15c116e-99e3-4c59-aebc-8f864929b4a0/resourceGroups/akswinvhdbuilderrg/providers/Microsoft.Compute/galleries/WS2022Gen2Gallery220902/images/windows-2022-containerd/versions/1.0.0"`

**Comment by wanqingfu** [comment]
Fixed here https://github.com/Azure/AgentBaker/pull/2153.

@HDYA
