### ISSUE TITLE
Allow us to turn off Mariner's equivalent of unattended upgrade

### ISSUE THREAD

**Issue by paulgmiller** [Azure/AgentBaker#2257]
**Is your feature request related to a problem?/Why is this needed**
We can turn off in ubuntu. If mariner has same functionality we should allow it to be turned off.
Don't think Windows has an equivalent. @AbelHu.

**Describe the solution you'd like in detail**
Honor NodeBootstrapingConfig's DisableUnattendedUpgrade and turn any automatic updates off. 

**Describe alternatives you've considered**
Daemonsets and remediators are fine but there is always a race with new images if we don't do it here.

**Additional context**

https://github.com/Azure/AgentBaker/pull/2175

**Comment by AbelHu** [comment]
We use [WindowsProfile.EnableAutomaticUpdates](https://github.com/Azure/AgentBaker/blob/master/pkg/agent/datamodel/types.go#L432)  to set it for Windows. The default value is false. AKS Windows users only can get the security patch by updating the node image version.
