### ISSUE TITLE
Images >2023.01.20 have duplicated /etc/machine-id

### ISSUE THREAD

**Issue by phealy** [Azure/AgentBaker#2725]
**What happened**:
Since image version 2023.01.20 /etc/machine-id is not being randomized per VM like it should be. [cleanup-vhd.sh](https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/packer/cleanup-vhd.sh) should empty the file during the build process but that doesn't seem to be working.

I deployed clusters using multiple image versions with 3 nodes each and got the machine IDs for each cluster:
```
2023.01.10:
1fbcae4dc8b24dd29ba2761ffa1975c0
b41324ebbd694f51aa9b5b1a104ba9f9
7b9cf358e3aa40a7a974946a29224a15

2023.01.19:
f012255033074f0984576b0b51b9f848
c853ec1fcab643b792d20cf9c9908627
8077caa0cab84596bfa084179cc083d3

2023.01.20:
de1dd9ede40041b7bceb409b0a3b12cb
de1dd9ede40041b7bceb409b0a3b12cb
de1dd9ede40041b7bceb409b0a3b12cb

2023.01.25:
c82bf5de25c44e56a41d3c75b74967d6
c82bf5de25c44e56a41d3c75b74967d6
c82bf5de25c44e56a41d3c75b74967d6

2023.01.26:
4813896e0be44568a53fb331dcb4af79
4813896e0be44568a53fb331dcb4af79
4813896e0be44568a53fb331dcb4af79

2023.02.01:
8b30ea1c06764b83aef59f790313e369
8b30ea1c06764b83aef59f790313e369
8b30ea1c06764b83aef59f790313e369
```

**What you expected to happen**:
/etc/machine-id should be different on every AKS node. This is visible in .status.nodeInfo.machineID:

```
$ kubectl explain node.status.nodeInfo
KIND:     Node
VERSION:  v1

RESOURCE: nodeInfo <Object>

DESCRIPTION:
     Set of ids/uuids to uniquely identify the node. More info:
     https://kubernetes.io/docs/concepts/nodes/node/#info

     NodeSystemInfo is a set of ids/uuids to uniquely identify the node.
```

**How to reproduce it**:
Deploy an AKS cluster with multiple nodes on image version >= 2023.01.20, look at machineID.

**Anything else we need to know?**:

**Environment**:
- AgentBaker version: whatever's in RP release v20230115
- Kubernetes version (use `kubectl version`): v1.24.9
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cameronmeissner** [comment]
fixed in https://github.com/Azure/AgentBaker/pull/2756
