### ISSUE TITLE
Add more Container Platform logs to collect-windows-logs.ps1

### ISSUE THREAD

**Issue by kiashok** [Azure/AgentBaker#2733]
Add more containerd logs to collect-windows-logs.ps1 to help troubleshooting for Container Platform team.

We would like the following data to be collected by default with collect-windows-log.ps1 script when ICMs are filed. This will reduced some back and forth with the cx to collect additional data for us to look into:

1) cd '.\Program Files\containerd\'
2) .\containerd.exe --v
3) .\crictl.exe pods
4) .\ctr.exe c ls
5) .\shimdiag.exe list
6) for each row got from (5), run the following and share outputs got for each:
   .\shimdiag.exe stacks <id got from each row in (5)> 
7) .\ctr.exe snapshot ls
8) .\crictl images
9)  get-process containerd-shim-runhcs-v1
10) get-process CExecSvc
11) Get-Process vmcompute

**Comment by AbelHu** [comment]
@junjiezhang1997 I think that we also need to update https://github.com/Azure/AgentBaker/blob/master/staging/cse/windows/provisioningscripts/loggenerator.ps1.

**Comment by kiashok** [comment]
From the recent ICMs, we noticed that having total commit memory of a container would be really helpful to have as part of the logs too. Can we add something like the following to collect total commit memory consumed by all the process in the container by session id?
get-process | group-object -property si | foreach-object { new-object psobject -property @{ SessionID=$_.Name; Memory=($_.Group.PagedMemorySize64 | measure-object -sum).Sum } } | format-table

**Comment by kiashok** [comment]
The following information will also be very helpful to have:

kubectl get nodes -o wide
kubectl top nodes
kubectl top pods
kubectl get events -n kube-system

**Comment by junjiezhang1997** [comment]
For the first comment, I think we can add it in both collect-windows-logs.ps1 and loggenerator.ps1. My only question is the result of your command only shows memory and session id as follows. Is it enough?

|  Memory | SessionID |
|    ------ | --------- |
|  66633728 | 10 |
|  64245760 | 11 |
| 1105395712 | 0 |
|  25440256 | 2 |
|  25530368 | 3 |
|  25284608 | 4 |
|  66252800 | 5 |
|  58503168 | 7 |
|  57171968 | 6 |
|  59957248 | 9 |
|  60559360 | 8 |
|  15704064 | 1 |

For the second comment, I'm sorry that we could not implement it since collect-windows-logs.ps1 runs in a windows node and those kubectl commands should be executed at the outside of a node. Of course, we think these commands are really helpful and we add them into our TSG page to help customer supportors or pg engineers collect logs.

**Comment by kiashok** [comment]
> For the first comment, I think we can add it in both collect-windows-logs.ps1 and loggenerator.ps1. My only question is the result of your command only shows memory and session id as follows. Is it enough?
> 
> Memory	SessionID
> 66633728	10
> 64245760	11
> 1105395712	0
> 25440256	2
> 25530368	3
> 25284608	4
> 66252800	5
> 58503168	7
> 57171968	6
> 59957248	9
> 60559360	8
> 15704064	1
> For the second comment, I'm sorry that we could not implement it since collect-windows-logs.ps1 runs in a windows node and those kubectl commands should be executed at the outside of a node. Of course, we think these commands are really helpful and we add them into our TSG page to help customer support or pg engineers collect logs.

For the first comment, I think I wanted to collect the total commit memory of every container running in the windows node. The aggregation is correct, but it would help to associate it with the containers that are running in the system (that is, which container is which session id). We should exec into the container to get information about the session id of a container and co-ordinate the container id with the output got from the command. Not sure if there is a better way to do this on AKS windows nodes? Let me think. @AbelHu thoughts? Do you know alternate ways to get this information?

**Comment by AbelHu** [comment]
@kiashok I think that we may not be able to collect such info in loggenerator.ps1. But it may be possible to collect it in collect-windows-logs.ps1 since normally it means that the node is bad when running collect-windows-logs.ps1. Could you help to provide the commands to us so @junjiezhang1997 can help to add it in the script?

**Comment by kiashok** [comment]
> @kiashok I think that we may not be able to collect such info in loggenerator.ps1. But it may be possible to collect it in collect-windows-logs.ps1 since normally it means that the node is bad when running collect-windows-logs.ps1. Could you help to provide the commands to us so @junjiezhang1997 can help to add it in the script?

Hi Abel, based on the meeting we had yesterday to retrieve commit memory, i think we can hold off from adding the commit memory usage in this script. Looks like there could be additional work needed to support it

**Comment by kiashok** [comment]
> The following information will also be very helpful to have:
> 
> kubectl get nodes -o wide kubectl top nodes kubectl top pods kubectl get events -n kube-system

Hi @junjiezhang1997 do you know if these commands were added to AKS TSGs like you suggested in this comment - https://github.com/Azure/AgentBaker/issues/2733#issuecomment-1443329794? I am working on few ICMs where having this information would have really helped. They are currently missing from the logs shared by CSS.

**Comment by kiashok** [comment]
One last commands that I think will be useful is -
.\hcsdiag.exe

**Comment by junjiezhang1997** [comment]
Oh, these commands are already added into TSG pages. But I think we and CSS miss them recently. I will clarify these commands with my colleagues and CSS. Thanks for reminding.
