### ISSUE TITLE
5 sysctls do not correctly respect AKS defaults when using custom node config

### ISSUE THREAD

**Issue by UtheMan** [Azure/AgentBaker#2866]
**What happened**:
When creating nodepools in AKS cluster using Custom Node config when all the values for following sysctls are not explicitly provided:

- net.core.somaxconn
- net.ipv4.tcp_max_syn_backlog
- net.ipv4.neigh.default.gc_thresh1
- net.ipv4.neigh.default.gc_thresh2
- net.ipv4.neigh.default.gc_thresh3

will cause the AKS default values to not be added.

**What you expected to happen**:
All 5 sysctls should be assigned to their default AKS value when not explicitly overwritten:

- net.core.somaxconn=16384
- net.ipv4.tcp_max_syn_backlog=16384
- net.ipv4.neigh.default.gc_thresh1=4096
- net.ipv4.neigh.default.gc_thresh2=8192
- net.ipv4.neigh.default.gc_thresh3=16384

**How to reproduce it**:
Create AKS cluster/Nodepool using Custom Node Config and ommit one of the mentioned values from supplied custom node config. The defaults will not be applied correctly. 

**How it can be fixed manually**:

Explicitly set all the values to their AKS default or value you need, for example: 
- net.core.somaxconn=16384
- net.ipv4.tcp_max_syn_backlog=16384
- net.ipv4.neigh.default.gc_thresh1=4096
- net.ipv4.neigh.default.gc_thresh2=8192
- net.ipv4.neigh.default.gc_thresh3=16384

More info about defaults and custom node config [here](https://learn.microsoft.com/en-us/azure/aks/custom-node-configuration)

**Comment by cameronmeissner** [comment]
I believe this was fixed
