### ISSUE TITLE
Upgrade Linux Containerd to 1.7.4

### ISSUE THREAD

**Issue by zhiweiv** [Azure/AgentBaker#3564]
We have Containerd shim leak issue in recent months(MS support case **2307180060001083**), seems it is fixed in Containerd 1.7.4, this issue has big impact in our use case. Do you have plan to upgrade Containerd？

https://github.com/containerd/containerd/releases/tag/v1.7.4
https://github.com/containerd/containerd/pull/9003

**Comment by AbelHu** [comment]
@zhiweiv, AKS tried to pick up Windows containerd 1.7 but is blocked by some issues in containerd 1.7. Could you file an issue in https://github.com/containerd/containerd to ask to backport this fix to containerd v1.6?

**Comment by zhiweiv** [comment]
Actually the issue is on Linux node, not Windows this time.

**Comment by zhiweiv** [comment]
Any update?

**Comment by ganeshkumar5699** [comment]
@zhiweiv, @AbelHu, for Ubuntu 22.04 and 20.04, latest images already use containerd1.7.5: https://github.com/Azure/AgentBaker/blob/343912a3938835dc5293249718f1a8785cdde334/parts/linux/cloud-init/artifacts/manifest.json#L10C18-L10C26, so that should have the fix

**Comment by zhiweiv** [comment]
Confirmed AKSUbuntu-2204gen2containerd-202310.04.0 brings containerd://1.7.5-1, thanks very much.
