### ISSUE TITLE
Not usable anymore outside MSFT or standalone project

### ISSUE THREAD

**Issue by mjudeikis** [Azure/AgentBaker#3810]
**What happened**:

After the introduction of https://github.com/Azure/AgentBaker/pull/3792 this project is not usable outside Microsoft infrastructure. We use this project to do security scans of Azure image structure and configurations, run tests and overlay configuration for some of our BYO nodes. 

Now to build windows nodes you need access to MSFT managed identity and private packages. 

**What you expected to happen**:

Opensource stay open :) 

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- AgentBaker version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by AbelHu** [comment]
We need to test or build windows vhds for some urgent fixes. Those URLs will be public finally so it will not block you.

**Comment by mjudeikis** [comment]
The blocking now is that without MSI you can't even run builds anymore. It's required variable now to be able to run packer build.

**Comment by mjudeikis** [comment]
Would something like this would work? 
https://github.com/Azure/AgentBaker/pull/3818
Use MSI only for private packages pull. This way we could run same build flow and it still works. As not despite the fact packages will be public at some point, builds are not runnable anymore as MSI identity takes over in env variables.

**Comment by mjudeikis** [comment]
@junjiezhang1997  let me know if you have any questions

**Comment by junjiezhang1997** [comment]
@mjudeikis Sorry for the late reply. I'm just preparing the pull request to fix it.

**Comment by junjiezhang1997** [comment]
@mjudeikis I tried the method you mentioned in #3818, but our pipeline failed with error "Identity not found" when trying to download private packages with msi. Also I tried to set the default value of msi string as empty and it also failed because it's not a valid msi string. I think I need more time to find the solution. Maybe you could set the variable "AZURE_MSI_RESOURCE_STRING" in your pipeline to mitigate this issue?

**Comment by mjudeikis** [comment]
I think this means we need to start using MSI for these builds as packer will try to inject this into the build VM, so this must be valid MSI. WIll need to check how hard is to re-engineer our pipelines for this. Will let you know in a day or so.

**Comment by junjiezhang1997** [comment]
@mjudeikis I think #3827 could solve this issue. Could you help test my branch on your pipelines? Thanks!

**Comment by mjudeikis** [comment]
Checking now

**Comment by mjudeikis** [comment]
Worked like a charm :)

**Comment by mjudeikis** [comment]
Fixed
