### ISSUE TITLE
CSEResultFilePath does not produce any file

### ISSUE THREAD

**Issue by stgleb** [Azure/AgentBaker#4170]
Despite providing CSEResultFilePath nothing is created on this path

**Environment**:
- AgentBaker version:
- Kubernetes version (use `1.27.9`):
- OS Windows19:
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by AbelHu** [comment]
@stgleb do you mean `CSEResultFilePath ` in Windows CSE? I think that it has been fixed in https://github.com/Azure/AgentBaker/pull/4158
