### ISSUE TITLE
AKS Log Collector doesn't collect Cilium logs

### ISSUE THREAD

**Issue by axelgMS** [Azure/AgentBaker#4327]
**What happened**:   Looks like there's a typo in the /var/log/ location for the cilium-cni logs.

**What you expected to happen**:

https://github.com/arc9693/AgentBaker/blob/master/parts/linux/cloud-init/artifacts/aks-log-collector.sh#L180C1-L181C1

collects logs in 
    **GLOBS+=(/var/log/cillium-cni*)**

but the logs seem to actually lie in 
    **GLOBS+=(/var/log/cilium-cni*)**

cf: 05-cilium.conflist

{
    "cniVersion": "0.3.1",
    "name": "cilium",
    "plugins": [
        {
            "type": "cilium-cni",
            "ipam": {
                "type": "azure-ipam"
            },
            "enable-debug": true,
            **"log-file": "/var/log/cilium-cni.log"**
        }
    ]
}

and

_root@aks-nodepool1-46355595-vmss000000:**/var/log**# ls -l  | grep cil
-rw-r--r--   1 root    root                9093 Apr 22 14:34 **cilium-cni.log**
root@aks-nodepool1-46355595-vmss000000:/var/log#
root@aks-nodepool1-46355595-vmss000000:/var/log#
root@aks-nodepool1-46355595-vmss000000:/var/log#
root@aks-nodepool1-46355595-vmss000000:/var/log# **cat cilium-cni.log**
level=debug msg="Processing CNI ADD request &skel.CmdArgs{ContainerID:\"44e5cbfa7bafb255dc016271a4ba04cf1fd7b8a2ca65f8abddc89f4caee4453d\", Netns:\"/var/run/netns/cni-6fbe0e49-2928-1345-3510-0cf3375c4702\", IfName:\"eth0\", Args:\"K8S_POD_NAMESPACE=kube-system;K8S_POD_NAME=coredns-767bfbd4fb-pm4vz;K8S_POD_INFRA_CONTAINER_ID=44e5cbfa7bafb255dc016271a4ba04cf1fd7b8a2ca65f8abddc89f4caee4453d;K8S_POD_UID=fafdc602-4edc-40ae-aa51-074e5faf5cd1;IgnoreUnknown=1\", Path:\"/opt/cni/bin\", StdinData:[]uint8{0x7b, 0x22, 0......_

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- AgentBaker version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cameronmeissner** [comment]
fixed in https://github.com/Azure/AgentBaker/pull/4185
