### ISSUE TITLE
Azure CLI missing from Node Image gen2/2204containerd/202406.19.0

### ISSUE THREAD

**Issue by aolear-ss** [Azure/AgentBaker#4568]
**What happened**:

After adding a new Node Pool to an AKS cluster in a nonproduction environment, workloads using the azure-blob-fuse storage class fail in "ContainerCreating" with the following error message:
``` 
MountVolume.MountDevice failed for volume "***" :   rpc error: code = Internal desc = Mount failed with error: rpc error: code =   Unknown desc = exit status 1 Error: failed to initialize new pipeline [Azure CLI not found on path]
```

Upon logging into the node, it is confirmed that the Azure CLI is not installed. After manually installing Azure CLI onto the node, the error message is resolved. 

It seems that the utility is missing from the node image version.

**What you expected to happen**:

The azure-blob-fuse storage class to work and for the pod to be started successfully.

**How to reproduce it**:

Deploy a pod that mounts a volume based on the "azureblob-fuse-premium" storage class.

**Anything else we need to know?**:

I'm not sure if this is the right place. The node version showing for the node pool is: 
![image](https://github.com/Azure/AgentBaker/assets/143454796/2fd2e5fb-f9cb-429e-a241-e89331fe0ee7)

Looking at the https://github.com/Azure/AKS/releases page, that version does not appear to exist. I do see it in this repository, which I found by following the links [here](https://releases.aks.azure.com/) for 202406.19.0 so I'm making the assumption that new versions are pushed from here and that page is not updated yet. If I'm in the wrong spot, I welcome any points in the right direction so we can get this resolved before it happens to a production cluster.

**Environment**:

N/A?

**Comment by cameronmeissner** [comment]
This is actually an upstream issue caused by this change: https://github.com/Azure/azure-storage-fuse/pull/1384, which relies on the Azure CLI being installed.

We've never previously installed the Azure CLI on any official AKS node images.

**Comment by aolear-ss** [comment]
Great - thank you both for the response. I did end up creating a daemonset to do just that, and that does work for now. Not ideal - but should hold us over until the permanent fix is available.

Thanks again!

**Comment by sigitas-plk** [comment]
@cameronmeissner not sure on exact reasons, but we have a cluster with node patching disabled which results in same exact blob csi plugin version working with **AKSUbuntu-2204gen2arm64containerd-202406.25.0** but failing with missing CLI error for **AKSUbuntu-2204gen2arm64containerd-202406.25.0** (any new node pool we would add to cluster, as it will always use latest ubuntu). The only difference between the two deployments is the underlying node version (same deployment, same blob storage account and container, same AKS & blob csi plugin versions).

There might be a different underlying problem potentially?  

We also tried different AKS versions which upgraded / downgraded blob csi version - same errors. The only bit which seem to make a difference - older ubuntu vm image.

**Comment by aolear-ss** [comment]
We were able to update to use `AzureStorageIdentityClientID` and remove our temporary solution installing the Azure CLI based on additional discussion here: https://github.com/Azure/AKS/issues/4375. Going to close this issue.

Thanks again for the assistance!
