### ISSUE TITLE
vmssCSE exit status 50 with a firewall blocking AAAA/IPV6 record

### ISSUE THREAD

**Issue by axelgMS** [Azure/AgentBaker#497]
Wanted your quick opinion on the exit status 50 with AKS vmssCSE below.  Incident 218837180

Customer has rules to block AAAA/IPV6 record on their firewall – and they were facing vmssCSE throwing exit status 50 - ERR_OUTBOUND_CONN_FAIL. 
I’m looking at the AgentBaker code – but I’m not finding any special dependencies on that.
	Does that ring something to you?
	Is there any reasons why we’d force calling mcr.microsoft.com through AAAA/IPv6?
	Any way to fall back to IPv4 in case we fail multiple times in a row (which would indicate customer has special config blocking IPv6)?

**Comment by xuto2** [comment]
cx should not disable AAAA
