### ISSUE TITLE
Update NVIDIA Device plugin version

### ISSUE THREAD

**Issue by sozercan** [Azure/AgentBaker#643]
NVIDIA Device plugin version is out of date, should be replaced by a new version.

https://github.com/Azure/AgentBaker/blob/master/vhdbuilder/packer/install-dependencies.sh#L280-L307

Image in MCR: `mcr.microsoft.com/oss/nvidia/k8s-device-plugin:v0.9.0` (yes, it goes backward 😀 )

**Comment by xuto2** [comment]
ack.

**Comment by xuto2** [comment]
Fixed in https://github.com/Azure/AgentBaker/pull/670
