### ISSUE TITLE
Add nvidia GPU Release version in vhdbuilder release notes

### ISSUE THREAD

**Issue by msjelly** [Azure/AgentBaker#721]
Please add GPU Release version in the vhdbuild release notes.

**Comment by msjelly** [comment]
e.g.  Add "nvidia gpu driver 450.x.y" to vhdbuild release notes file vhdbuilder/release-notes/AKSUbuntu/gen2/1804gpu/yyyy.mm.dd.txt

**Comment by xuto2** [comment]
ack.

**Comment by anujmaheshwari1** [comment]
Hi @msjelly, here is the PR for adding the Nvidia GPU version to the release notes. 
https://github.com/Azure/AgentBaker/pull/770

Also, here is an example of the new updated release notes file. 
https://msazure.visualstudio.com/CloudNativeCompute/_build/results?buildId=41736221&view=artifacts&pathAsName=false&type=publishedArtifacts

Please let me know if you have any concerns, thanks!
