### ISSUE TITLE
Refine windows-vhd-content-test.ps1 to use the same policy to filter k8s versions in configure-windows-vhd.ps1

### ISSUE THREAD

**Issue by AbelHu** [Azure/AgentBaker#824]
In configure-windows-vhd.ps1
```

            # Windows containerD supports Windows containerD, starting from Kubernetes 1.20
            if ($containerRuntime -eq 'containerd' -And $dir -eq "c:\akse-cache\win-k8s\") {
                $k8sMajorVersion = $fileName.split(".",3)[0]
                $k8sMinorVersion = $fileName.split(".",3)[1]
                if ($k8sMinorVersion -lt "20" -And $k8sMajorVersion -eq "v1") {
                    Write-Log "Skip to download $url for containerD is supported from Kubernets 1.20"
                    continue
                }
            }

```
But in windows-vhd-content-test.ps1, it uses two list to validate cached k8s versions. This is not convenient. I think that we can use the same policy as that in configure-windows-vhd.ps1

**Comment by mainred** [comment]
The implementation in windows-vhd-content-test.ps1 is expected. because we want to simplify the code in configure-windows-vhd.ps1, but we want to make sure all the k8s versions are clearly listed in each case. I mentioned this in my pr to have such a difference.

**Comment by AbelHu** [comment]
I saw the comments but it is not convenient so I think that we can do some improvement. Otherwise, we may forget to update some parts and waste the time.

**Comment by mainred** [comment]
It's useless for the test code we use the same code for business and tests.  I don't think it's inconvenient, k8s version win zip must  be100% sure what they are going to add, also they need only one addition/deletion in test for each k8s version
